spring:
  application:
    name: configserver

#  profiles:
#    active: default

  cloud:
    config:
      server:
        git:
          uri: https://github.com/nira-j/microservices-config.git
          search-paths: config
          default-label: main
server:
  port: 8888
## To enable Symmetric Key(simple) encryption/decryption
#encrypt.key=mysecretkey123

# To enable Asymmetric Key (RSA) encryption
#encrypt.key-store.location=classpath:mykeystore.jks
#encrypt.key-store.password=changeit
#encrypt.key-store.alias=mykey

## Disable access to /encrypt and /decrypt:
management:
  endpoints:
    web:
      exposure:
        exclude: encrypt,decrypt

#spring.cloud.config.server.native.search-locations=file:///E:/application-config/config

